### ISSUE TITLE
Mod not working.

### ISSUE THREAD

**Issue by Etherios55** [tristanmcpherson/KookehsItemDropMod#1]
I am unable to drop items in game. Currently have BepInExPack_a41001c_5.0.0.0_b22 installed and the bepin loader gives me the following text after your mod comes up: 

[Error  : Unity Log] MissingMethodException: void R2API.InventoryAPI.add_OnEquipmentIconAdded(System.Action`1<RoR2.UI.EquipmentIcon>)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by tristanmcpherson** [comment]
@Etherios55 Sorry about that, I have updated the README, it now requires BepInExPack_a41001c_5.0.0.0_b24 or newer. Sorry for the issues!
