### ISSUE TITLE
After playing for a bit the game starts lagging

### ISSUE THREAD

**Issue by 01davdav** [tristanmcpherson/KookehsItemDropMod#11]
After playing for a bit (around 1 to 2 stages) the game starts having a ~2 second freeze frame every ~5 seconds. The logs show a nullReferenceExcetion

**Comment by tristanmcpherson** [comment]
Thanks, I’ll look into it

**Comment by tristanmcpherson** [comment]
Should be fixed now, thanks for reporting! Let me know if you see this still, or have any other issues.

**Comment by tristanmcpherson** [comment]
Fixed in efabf508c348c5121678d2adc06fd0267a6d8e34

**Comment by 01davdav** [comment]
I've just tested it and it seems to be fixed! Thank you for the quick fix, love the mod.

**Comment by tristanmcpherson** [comment]
> I've just tested it and it seems to be fixed! Thank you for the quick fix, love the mod.

glad you enjoy it! And no problem
