### ISSUE TITLE
Mod not working after latest patch

### ISSUE THREAD

**Issue by DavidJGH** [tristanmcpherson/KookehsItemDropMod#13]
When you click on an item after updating to the latest patch you only get an error in the console and nothing happens

**Comment by tristanmcpherson** [comment]
Thanks, I'll look into this soon and fix it

**Comment by Elvarion** [comment]
I actually cant even get this work even with only the following modlist:

_Picking up an item, then holding tab and leftclick on either the top row or the Tab window row. neither does anything. Ive had this working prior to the last Vanilla Ror2 Update_

- BepinExPack (5.4.1905)
- HookGenPatcher (1.2.3)
- R2API (4.3.5)
- KookehsDropItem_BepInEx (2.3.2)

Great mod when playing in multiplayer so we really miss it at the moment ^^

**Comment by tristanmcpherson** [comment]
Yeah, it’s definitely broken in the current patch. I’ll try to remember to fix it tonight. Thanks for enjoying the mod!

**Comment by tristanmcpherson** [comment]
> When you click on an item after updating to the latest patch you only get an error in the console and nothing happens

Can you send me the error?

**Comment by mhaapaniemi** [comment]
[Error: Unity Log] MissingFieldException: Field 'RoR2.ItemDef.tier' not found.

**Comment by tristanmcpherson** [comment]
@Elvarion @DavidJGH Are either of you available to help me test a build? I can't seem to get my local modded to work properly

**Comment by tristanmcpherson** [comment]
[KookehsDropItemMod (2).zip](https://github.com/tristanmcpherson/KookehsItemDropMod/files/8566966/KookehsDropItemMod.2.zip)

**Comment by tristanmcpherson** [comment]
[KookehsDropItemMod (2).zip](https://github.com/tristanmcpherson/KookehsItemDropMod/files/8566970/KookehsDropItemMod.2.zip)

**Comment by tristanmcpherson** [comment]
Fixed in: ecb52590d6f7e1bebaec2977e7574515a3e7b1b3
I've pushed a release, you should be able to update now. Thanks for reporting this!
https://thunderstore.io/package/tristanmcpherson/KookehsDropItem_BepInEx/

**Comment by DavidJGH** [comment]
Sorry, wasn't available, but I just tested the updated version and everything seems to be working again! ty!

**Comment by tristanmcpherson** [comment]
> Sorry, wasn't available, but I just tested the updated version and everything seems to be working again! ty!

Awesome! I pushed a version to the store so everything should be working now. Thanks for reporting this :)

**Comment by Elvarion** [comment]
Sorry, I was on a business trip 🧑‍💼  
Can also confirm the version on Thunderstore is working as it should :)
Thanks for the updated version!
