### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by goulmurash** [tristanmcpherson/KookehsItemDropMod#2]
i updated bepinex load the game try to drag items pressed a bunch of keys i still have no clue how the mod works or if it even works. it would be really awesome to have this mod working the number time ive picked up something i didnt need but someone else did, this mod would be a savior.

**Comment by tristanmcpherson** [comment]
What version of BepInExPack did you use? @goulmurash

**Comment by goulmurash** [comment]
the one linked in im sorry i didnt reply i managed to make it work one of
the file didnt get changed i though it would get replaced if i just put it
in there but i had to completly delete bepinex and put it in did that an
hour ago thnks for the reply tho

**Comment by goulmurash** [comment]
you should add that if people put to many item out of their inventory at
the same time it might crash their game
i was about  to leave a game gave everything i had and it crashed everyones
game


Le ven. 19 avr. 2019, à 00 h 17, Olivier Kenneth <goulmurash@gmail.com> a
écrit :

> the one linked in im sorry i didnt reply i managed to make it work one of
> the file didnt get changed i though it would get replaced if i just put it
> in there but i had to completly delete bepinex and put it in did that an
> hour ago thnks for the reply tho
>
> Le jeu. 18 avr. 2019, à 22 h 52, Tristan McPherson <

**Comment by tristanmcpherson** [comment]
Oh really? Ill try to see what that is to prevent that. I haven't seen that
before. If you do happen to see it and can copy your logs from
AppData/LocalLow/Hopoo Games, LLC/Risk of Rain 2/ that would help a ton.
Also, glad you got the mod working. The process should be easier soon.

Thanks!

**Comment by Ta1ha** [comment]
Goulmurash, were you the host? because if the host exits the game everyone's  game disconnects. It may not be cause of the mod.

**Comment by goulmurash** [comment]
no i wasnt they had the mod as well it just crashed before i even left


Le mer. 24 avr. 2019, à 14 h 48, Talha Ucar <notifications@github.com> a
écrit :

**Comment by tristanmcpherson** [comment]
Closing this issue as no other reports have been reported, and a new version has been released.
