### ISSUE TITLE
What are the controls?

### ISSUE THREAD

**Issue by xbamfo** [tristanmcpherson/KookehsItemDropMod#4]
Just wondering how I use this in-game. Click and Drag? Another button or key press? I've tried some on my own and had no luck.
The readme could be updated with that instruction.

It's possible the mod is not functioning due to a conflict with something else, but I can't tell as I am not sure how it is *supposed* to work.

**Comment by tristanmcpherson** [comment]
Good point. The lack of info was due to it being just a port but now that it's something different that's good to include. You just click on an item in your inventory either at the top of the screen or in the tab menu. Please send any error text you receive in the console if so. Also beware that RoR2 was just updated so that may be why.

**Comment by xbamfo** [comment]
Ah yeah. It's not working currently, likely because of the update. I've been going through the game testing the mods I had already and seeing which ones still work and which ones gained some issues. Seems most are luckily unaffected, but some new conflicts may have arrived.
I was seeing some error code related to engineer fixes (lunar coins). I believe that may have been fixed and now it's no longer necessary, and now bepinex is confused.
I'm going to try again and work through as much errors as I can to see if I can give you more info :)

**Comment by xbamfo** [comment]
I'm not going to be able to give coding information tonight i'm afraid, just got an email that my apartment is being inspected tomorrow. Time for a cleaning spree x-x.

All I can do is confirm that the mod does not appear to be functioning for me at this time.
Here is my list of other mods for any further information, sorry I'll have to be busy for a while. Hope it helps.
[https://i.imgur.com/3KoxTBM.png](Screenshot 1)
[https://i.imgur.com/xpWACkv.png](Screenshot 2)

**Comment by RagnarTheRagnar** [comment]
There was another update and I see the same issue. When I attempt to click on the items its just does a M1 click and does an attack. I didn't pull any logs or anything like that.

**Comment by tristanmcpherson** [comment]
@RagnarTheRagnar I'll take a look at it tonight, probably something simple.

**Comment by tristanmcpherson** [comment]
@RagnarTheRagnar @xbamfo New release is out. Enjoy!
