### ISSUE TITLE
No longer working after v1.0 Update

### ISSUE THREAD

**Issue by VirtualSmile** [tristanmcpherson/KookehsItemDropMod#9]
Hello!

After the 1.0 Update, this mod no longer works. Clicking on the items have no effect.

I'd like to request an update for this mod! It's super useful in both singleplayer and my multiplayer runs with mates.

Thank you~

**Comment by tristanmcpherson** [comment]
Ahh, sorry about that. I'll try to get it fixed for ya soon, glad you enjoy the mod!

**Comment by tristanmcpherson** [comment]
Please update to the newest version and let me know if you have any issues. Thanks!
